<?php

namespace appbox\adminBundle\Repository;

/**
 * contactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contactRepository extends \Doctrine\ORM\EntityRepository
{
    public function message()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.vue = :vue')
            ->setParameter('vue',false);

        return $qb->getQuery()->getResult();

    }

    public function inbox()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->orderBy('c.id','desc');

        return $qb->getQuery()->getResult();

    }
}
