# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        appbox\UserBundle\Entity\user: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_log:
            pattern: /blog/login
            anonymous: true
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                    twitter:            "/login/check-twitter"
                login_path:        /bl/login
                failure_path:      /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge
            logout:
                path:       fos_user_security_logout
                target:     /
    access_control:
        - { path: ^/paiement, role: ROLE_USER }
        - { path: ^/supcomentaire, role: ROLE_USER }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/gc, role: ROLE_SUPER_ADMIN }
