<?php

namespace appbox\voyageBundle\Repository;

/**
 * blogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blogRepository extends \Doctrine\ORM\EntityRepository
{
    public function blogforindex()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->orderBy('b.id', 'desc')
            ->setMaxResults(1);
        return $qb->getQuery()->getResult();

    }
    public function footerblog(){
        $qb = $this->createQueryBuilder('b');
        $qb->orderBy('b.id', 'desc')
            ->setMaxResults(2);
        return $qb->getQuery()->getResult();
    }
}
