<?php

namespace appbox\voyageBundle\Repository;

/**
 * EmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeRepository extends \Doctrine\ORM\EntityRepository
{

    public function Allemployee()
    {
        $qb = $this->createQueryBuilder('e');
        $qb->addorderBy('e.etat','asc')
            ->addorderBy('e.name','asc');

        return $qb->getQuery()->getResult();

    }
}
