<?php

namespace appbox\voyageBundle\Repository;

/**
 * galerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class galerieRepository extends \Doctrine\ORM\EntityRepository
{
    public function galerieforonevoyage($id)
    {
        $qb = $this->createQueryBuilder('g');
        $qb->where('g.voyage = :id')
            ->setParameter('id',$id);
        return $qb->getQuery()->getResult();

    }
}
