<?php

namespace appbox\voyageBundle\Repository;

/**
 * optiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class optiRepository extends \Doctrine\ORM\EntityRepository
{
}
