<?php

namespace appbox\voyageBundle\Repository;

/**
 * personne_voitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personne_voitureRepository extends \Doctrine\ORM\EntityRepository
{
}
