<?php

namespace appbox\voyageBundle\Repository;

/**
 * reservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function reservationparidprofil($id)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->where('r.user = :id')
            ->setParameter('id',$id)
            ->orderBy('r.id', 'desc');
        return $qb->getQuery()->getResult();

    }
}
