<?php

namespace appbox\voyageBundle\Repository;

/**
 * reviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function reviewforvoyage($id)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->where('r.voyage = :id')
            ->setParameter('id',$id)
            ->orderBy('r.date', 'desc');
        return $qb->getQuery()->getResult();

    }
}
