<?php

namespace appbox\voyageBundle\Repository;

/**
 * voyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class voyageRepository extends \Doctrine\ORM\EntityRepository
{
}
